#pragma once

typedef enum {
    UI_PAGE_HOME = 0,
    UI_PAGE_QUICK_MENU,
    UI_PAGE_SETTINGS,
    UI_PAGE_STATUS,
} ui_page_t;

typedef enum {
    UI_STATUS_ITEM_LCD = 0,
    UI_STATUS_ITEM_TOUCH,
    UI_STATUS_ITEM_AUDIO,
    UI_STATUS_ITEM_SD,
    UI_STATUS_ITEM_WIFI_C6,
    UI_STATUS_ITEM_CAMERA,
    UI_STATUS_ITEM_BH1750,
    UI_STATUS_ITEM_VL6180X_L,
    UI_STATUS_ITEM_VL6180X_C,
    UI_STATUS_ITEM_VL6180X_R,
    UI_STATUS_ITEM_IMU,
    UI_STATUS_ITEM_MOTION,
} ui_status_item_t;

typedef enum {
    UI_MOTION_STATUS_LOCKED = 0,
    UI_MOTION_STATUS_READY,
    UI_MOTION_STATUS_MOVING,
    UI_MOTION_STATUS_FAULT,
} ui_motion_status_t;
