#pragma once

typedef enum {
    SPEECH_COMMAND_NONE = 0,
    SPEECH_COMMAND_WAKE,
    SPEECH_COMMAND_SLEEP,
    SPEECH_COMMAND_START_FOCUS,
    SPEECH_COMMAND_STOP_FOCUS,
    SPEECH_COMMAND_LIGHT_UP,
    SPEECH_COMMAND_LIGHT_DOWN,
    SPEECH_COMMAND_SET_REMINDER,
    SPEECH_COMMAND_CANCEL_REMINDER,
    SPEECH_COMMAND_PERSONA_SWITCH,
    SPEECH_COMMAND_QUIETER,
    SPEECH_COMMAND_STATUS,
} speech_command_id_t;
