#pragma once

typedef enum {
    SPEECH_COMMAND_NONE = 0,
    SPEECH_COMMAND_WAKE,
    SPEECH_COMMAND_SLEEP,
    SPEECH_COMMAND_STATUS,
    SPEECH_COMMAND_VOLUME_UP,
    SPEECH_COMMAND_VOLUME_DOWN,
    SPEECH_COMMAND_MUTE,
    SPEECH_COMMAND_UNMUTE,
    SPEECH_COMMAND_CONFIRM,
} speech_command_id_t;

